name: Release Pipeline

on:
  push:

jobs:
  release-pipeline:
    name: Release Pipeline
    runs-on:
      - windows-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Setup dotnet tools
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Run Core.Test
        run: dotnet test .\src\DevOpsDaysTasks.Core.Tests